<?php

namespace Container0RXlNK5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TEbuycHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TEbuycH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TEbuycH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stockHistoricRepository' => ['privates', 'App\\Repository\\StockHistoricRepository', 'getStockHistoricRepositoryService', true],
        ], [
            'stockHistoricRepository' => 'App\\Repository\\StockHistoricRepository',
        ]);
    }
}
