<?php

namespace Container0RXlNK5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZPCXaRXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zPCXaRX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zPCXaRX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stockHistoric' => ['privates', '.errored..service_locator.zPCXaRX.App\\Entity\\StockHistoric', NULL, 'Cannot autowire service ".service_locator.zPCXaRX": it references class "App\\Entity\\StockHistoric" but no such service exists.'],
        ], [
            'stockHistoric' => 'App\\Entity\\StockHistoric',
        ]);
    }
}
