<?php

namespace Container0RXlNK5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStockHistoricService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LBuiBjb.App\Entity\StockHistoric' shared service.
     *
     * @return \App\Entity\StockHistoric
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.LBuiBjb": it references class "App\\Entity\\StockHistoric" but no such service exists.');
    }
}
