<?php

namespace ContainerFQxIyxO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7P87fGMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7P87fGM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7P87fGM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'category' => ['privates', 'App\\Entity\\Category', 'getCategoryService', true],
        ], [
            'category' => 'App\\Entity\\Category',
        ]);
    }
}
